version: "3"
services:
  ## ======
  ## Server
  ## ======

  miyuki-server:
    links:
      - miyuki-haskell-runner
    volumes:
      - ./development.sqlite3:/var/www/miyuki/db/production.sqlite3
    depends_on:
      - miyuki-haskell-runner

  ## =======
  ## Runners
  ## =======

  miyuki-haskell-runner:
    image: flbulgarelli/miyuki-haskell-runner
    container_name: miyuki-haskell-runner
    privileged: true
    volumes:
      - /tmp:/tmp
    command: bundle exec puma -p 3030
    ports:
      - 3030:3030
    depends_on:
      - miyuki-dind

  ## =======
  ## Workers
  ## =======

  miyuki-haskell-worker-setup:
      image: flbulgarelli/miyuki-haskell-runner
      container_name: miyuki-haskell-worker-setup
      restart: "no"
      privileged: true
      command: bundle exec ruby pull_worker.rb
      depends_on:
        - miyuki-dind
