# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3


common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: mumuki
  password: mumuki

test:
  <<: *common
  database: mumuki_old_test
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: mumuki_old_development
  pool: 5
  timeout: 5000
