name: Packager Release
on:
  push:
    tags:
      - '**/*'
jobs:
  pack-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packager

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: './packager/.nvmrc'

      - name: Extract DIST_NAME from tag
        run: |
          TAG="${{ github.ref_name }}"
          DIST_NAME="${TAG%%/*}"
          echo "DIST_NAME=$DIST_NAME" >> $GITHUB_ENV

      - run: npm install

      - name: Run make with DIST_NAME
        run: npm run make
        env:
          DIST_NAME: ${{ env.DIST_NAME }}

      - name: Crear release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "./packager/out/make/deb/x64/**"
          token: ${{ secrets.GITHUB_TOKEN }}

  pack-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./packager

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: './packager/.nvmrc'

      - name: Extract DIST_NAME from tag
        shell: bash
        run: |
          TAG="${{ github.ref_name }}"
          DIST_NAME="${TAG%%/*}"
          echo "DIST_NAME=$DIST_NAME" >> $GITHUB_ENV

      - run: npm install
      
      - name: Run make with DIST_NAME
        run: npm run make
        env:
          DIST_NAME: ${{ env.DIST_NAME }}

      - name: Crear release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "./packager/out/make/squirrel.windows/x64/*.exe"
          token: ${{ secrets.GITHUB_TOKEN }}